from flask import Flask, request, jsonify
from flask_cors import CORS
from google import genai
from google.genai import types
from supabase import create_client    # ← make sure this line exists
import requests as req                
import base64
import json
import re

app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})

# Gemini client
client = genai.Client(api_key="INSERT_GEMINI_KEY")

# Supabase config — REST API approach (no supabase package needed)
SUPABASE_URL = "INSERT_SUPABASE_URL_HERE"

# 🔑 Credentials split setup to bypass Row-Level Security blocks
SUPABASE_PUBLIC_ANON_KEY = "INSERT_PUBLIC_ANON_KEY_HERE"
SUPABASE_SERVICE_KEY = "INSERT_SERVICE_KEY_HERE"

# 🛡️ Database communication headers use the Service Role key to bypass RLS locks natively
SUPABASE_HEADERS = {
    "apikey": SUPABASE_SERVICE_KEY,
    "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation"
}

def extract_carbon_number(value_str):
    if not value_str:
        return 0.0
    match = re.search(r"[\d.]+", str(value_str))
    return float(match.group()) if match else 0.0

def get_user_from_token(auth_header):
    if not auth_header or not auth_header.startswith('Bearer '):
        print("❌ No auth header or wrong format")
        return None
    token = auth_header.replace('Bearer ', '')
    print(f"🔑 Token received (first 20 chars): {token[:20]}")
    try:
        response = req.get(
            f"{SUPABASE_URL}/auth/v1/user",
            headers={
                "apikey": SUPABASE_PUBLIC_ANON_KEY,
                "Authorization": f"Bearer {token}"
            }
        )
        if response.status_code == 200:
            user = response.json()
            print(f"✅ User verified: {user.get('email')}")
            return user
        print(f"❌ Auth failed: {response.status_code} {response.text}")
        return None
    except Exception as e:
        print(f"❌ Token error: {e}")
        return None

def supabase_insert(table, data):
    response = req.post(
        f"{SUPABASE_URL}/rest/v1/{table}",
        headers=SUPABASE_HEADERS,
        json=data
    )
    if response.status_code not in [200, 201]:
        print(f"❌ Insert error: {response.status_code} {response.text}")
    else:
        print(f"✅ Insert successful: Row committed directly via Admin Access.")
    return response

@app.route("/classify", methods=["POST"])
def classify():
    auth_header = request.headers.get('Authorization')
    user = get_user_from_token(auth_header)
    if not user:
        return jsonify({"error": "Unauthorized"}), 401

    data = request.get_json()
    image_data = data.get("image")
    mime_type = data.get("mime_type", "image/jpeg")

    if not image_data:
        return jsonify({"error": "No image provided"}), 400

    image_bytes = base64.b64decode(image_data)

    prompt = """You are a waste classification authority. Analyze this image and respond ONLY with a raw JSON object.

STRICT RULES:
- NO "it depends" or "check local guidelines". Give direct, concrete commands.
- If an item is NOT recyclable, return an empty list [] for recycle_steps.
- Each recycle_step and dispose_step must be 8-15 words long.
- Give exactly 4 steps for each category (unless the list is empty).
- Each fun_fact must be 12 words max. Give exactly 3.
- confidence: must be exactly 'high', 'medium', or 'low'.
- carbon_footprint: CO2 generated by producing this item, number with unit only e.g. 9.5 kg CO2.
- carbon_saved: CO2 saved by recycling instead of landfilling, number with unit only e.g. 8.1 kg CO2.

{
  "material": "specific material",
  "item_name": "common name",
  "category": "category",
  "confidence": "high/medium/low",
  "disposal": "Recyclable / Non-Recyclable",
  "impact": "10 words or less",
  "carbon_footprint": "number with unit",
  "carbon_saved": "number with unit",
  "did_you_know": "20 words or less",
  "fun_facts": ["fact 1", "fact 2", "fact 3"],
  "recycle_steps": ["step 1", "step 2", "step 3", "step 4"],
  "dispose_steps": ["step 1", "step 2", "step 3", "step 4"]
}"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[
            types.Content(
                role="user",
                parts=[
                    types.Part.from_bytes(
                        data=image_bytes,
                        mime_type=mime_type
                    ),
                    types.Part.from_text(text=prompt)
                ]
            )
        ]
    )

    raw = response.text
    clean = re.sub(r"```json|```", "", raw).strip()
    result = json.loads(clean)

    carbon_generated = extract_carbon_number(result.get("carbon_footprint"))
    carbon_saved = extract_carbon_number(result.get("carbon_saved"))

    # Save to Supabase via REST API
    supabase_insert("scan_results", {
        "user_id": user.get("id"),
        "item_name": result.get("item_name"),
        "material": result.get("material"),
        "category": result.get("category"),
        "disposal": result.get("disposal"),
        "carbon_generated": carbon_generated,
        "carbon_saved": carbon_saved,
        "confidence": result.get("confidence")
    })
    print(f"✅ Saved: {result.get('item_name')} | {carbon_generated} kg generated | {carbon_saved} kg saved | user: {user.get('id')}")

    return jsonify(result)

@app.route("/stats", methods=["GET"])
def stats():
    auth_header = request.headers.get('Authorization')
    user = get_user_from_token(auth_header)
    if not user:
        return jsonify({"error": "Unauthorized"}), 401

    try:
        range_param = request.args.get("range", "monthly")

        from datetime import datetime, timedelta, timezone
        now = datetime.now(timezone.utc)
        since = now - timedelta(weeks=1) if range_param == "weekly" else now - timedelta(days=30)
        
        # 🛠️ THE TIMESTAMP FIX: Use standard ISO trailing 'Z' instead of the +00:00 sign format
        since_str = since.isoformat().replace("+00:00", "Z")

        user_id = user.get("id")
        print(f"📊 Fetching stats for user: {user_id}")
        print(f"📅 Date filter: since {since_str}")

        # Query Supabase REST API directly
        url = (
            f"{SUPABASE_URL}/rest/v1/scan_results"
            f"?select=carbon_generated,carbon_saved,disposal,category,created_at"
            f"&user_id=eq.{user_id}"
            f"&created_at=gte.{since_str}"
        )

        response = req.get(url, headers=SUPABASE_HEADERS)
        rows = response.json()

        # Structural Guard check: If query response returns a dict error object instead of a data matrix array
        if isinstance(rows, dict) and "message" in rows:
            print(f"❌ Supabase Query Error payload: {rows}")
            return jsonify({"error": rows["message"]}), 400

        print(f"📦 Rows found: {len(rows)}")
        print(f"📦 Raw data: {rows}")

        total_carbon_generated = sum(float(r["carbon_generated"]) for r in rows if r.get("carbon_generated") is not None)
        total_carbon_saved = sum(float(r["carbon_saved"]) for r in rows if r.get("carbon_saved") is not None)
        total_scans = len(rows)
        recyclable_count = sum(1 for r in rows if r.get("disposal") and "recyclable" in r["disposal"].lower())

        print(f"✅ Generated: {total_carbon_generated} | Saved: {total_carbon_saved} | Scans: {total_scans}")

        return jsonify({
            "total_scans": total_scans,
            "total_carbon_generated": round(total_carbon_generated, 4),
            "total_carbon_saved": round(total_carbon_saved, 4),
            "recyclable_count": recyclable_count
        })

    except Exception as e:
        print(f"❌ Stats error: {e}")
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    print("Flask starting on port 5000...")
    app.run(debug=True, host="0.0.0.0", port=5000)
